### ISSUE TITLE
BlueUp UriBeacons

### ISSUE THREAD

**Issue by samueleforconi** [google/uribeacon#237] opened 2015-05-06 14:59 UTC
Hi, 
I'm the co-founder of an italian company, BlueUp ( http://www.blueupbeacons.com ), that is involved in BLE Beacons development and production.
We already have a catalogue of iBeacons devices (entirely designed and made in Italy) and now we are about to launch also some UriBeacons products. We have completed the development of the firmware for our device, so within a few days we should have the BlueUp UriBeacons in our catalogue.
I wonder if it's possible to use the UriBeacon logo on our web site and link the UriBeacon Specification.

Would it be possible for you to include our company in the list of the UriBeacons manufacturers on the main GitHub UriBeacon page?

Thanks.

Regards,
Samuele.

**Comment by g-ortuno** [comment] 2015-05-06 17:10
Great! Have you used the Validator App to make sure the beacon follows the spec?

https://github.com/google/uribeacon/releases/tag/v1.4

**Comment by samueleforconi** [comment] 2015-05-07 07:55
Hi, we are planning to carry out the tests within the next days because we are currently lacking an Android phone with BT4.0. 
We have already tested our UriBeacon FW implementation with the Physical Web app and with other iOS apps available on the App Store.
I hope we can make tests with the Android Validator App in the next days.
I'll post our test report as soon as we carried out tests with the Android Validator App.

**Comment by g-ortuno** [comment] 2015-05-07 17:46
Great! Let us know if you have any problems.

**Comment by samueleforconi** [comment] 2015-05-13 16:05
Hi,
we are trying to run the UriBeacon-Validator app on a Samsung Galaxy S4 phone running Android 4.4.2 but we the app stops immediately as soon as it is launched. 
Is there a special procedure to run this app? I have also tried to download the source code, recompile and run, but with no luck.

**Comment by g-ortuno** [comment] 2015-05-13 16:07
Sadly the validator app only works on Lollipop.

**Comment by samueleforconi** [comment] 2015-05-14 13:53
Hi,
we have tested our beacons using the Validator App and the Nordic nRF Master Control Panel.
The Validator App fails the last 3 tests, but I can't figure out why... 
![_screenshot_2015-05-14-15-44-02](https://cloud.githubusercontent.com/assets/6040113/7632879/1ba2ca22-fa51-11e4-8929-a68a689d1ebd.png)

With the nRF Master Control Panel we are able to detect the URI Beacon, read and write its characteristics values correctly.
![_screenshot_2015-05-14-15-41-33](https://cloud.githubusercontent.com/assets/6040113/7632933/5d97e7f0-fa51-11e4-8818-c13d1d8cea98.png)

**Comment by ucxpresso** [comment] 2015-05-14 13:58
FYI & Open Source:
http://www.embeda.com.tw/ucxpresso/?article=2-3-google-uribeacon-project

**Comment by g-ortuno** [comment] 2015-05-14 15:49
It seems that the problem isn't with configuring the beacon, but rather with the adv packet. From the screenshot it seems that the values written are not being broadcasted. The Validator wrote "0" for flags and was expecting to read a "0" from the adv packet but instead got a "1". Same for the rest of the fields.

**Comment by ukBaz** [comment] 2015-05-14 16:11
Those numbers that are being output in the last test on the validator app spell out "http://www.blue-up.it" which I suspect the validator isn't expecting. So I wonder if it is the setup that is failing.

**Comment by g-ortuno** [comment] 2015-05-14 16:22
Yeah. The values the validator wrote in the previous steps are not being broadcasted.

**Comment by samueleforconi** [comment] 2015-05-15 06:34
Ok, but why if I write those values using the Nordic nRF Master Control Panel or other apps (i.e. LightBlue for iOS), the values are correctly written and broadcasted in the advertising packet? 
I have just tried to configure the beacon with a different URI, TxPower Mode, Period, etc... and the advertising data is correctly set in the advertising packet (I checked the new URI with Physical Web app).

In my understanding, the Validator is trying to set URI Flags to "1" and receives "0", then for Tx Power Level it tries to set "0" and receives "-28", the same for the URI data.

With other apps the beacon configuration works correctly, what kind of write operations does the Validator app perform?

**Comment by ucxpresso** [comment] 2015-05-15 07:04
Do you have to update the adv. data after to configure your beacon? If yes, and How to?

**Comment by g-ortuno** [comment] 2015-05-15 16:09
Interesting. If I had to guess either Lock/Unlock or Reset is not implemented correctly. The other option is that you have beacons with the same address around so the validator gets confused.

You could try the following to see if you still fail the tests:

1. Go into "Core UriBeacon Tests"
2. Cancel the test by pressing back while the app looks for a configurable beacon.
3. Long press on "Write and Read Data"
4. Let tests go on.

This should skip Lock/Unlock and Reset.

**Comment by samueleforconi** [comment] 2015-05-27 14:54
Hi,
I've finally solved the issue with our UriBeacons and the UriBeacon Validator App. 
The problem was caused by the Reset characteristic that in our implementation was applied after the disconnection with the Central. 
Now our UriBeacons seem to be compliant with the specification.
We hope to become part of your UriBeacon suppliers list. :)

![screenshot_2015-05-26-12-56-27](https://cloud.githubusercontent.com/assets/6040113/7839020/7096f2d0-0490-11e5-860f-4f1be28a833d.png)

![screenshot_2015-05-14-15-45-09](https://cloud.githubusercontent.com/assets/6040113/7839022/770925fc-0490-11e5-8991-64ec10e062a6.png)

**Comment by g-ortuno** [comment] 2015-05-27 16:36
That's great! Do you have a link to your website where one could find UriBeacons?

**Comment by samueleforconi** [comment] 2015-05-28 14:59
You can find on this page all our beacons for sale: 
http://www.blueupbeacons.com/index.php?page=products

**Comment by g-ortuno** [comment] 2015-05-28 16:20
Done :smiley:

**Comment by schilit** [comment] 2015-06-28 17:41
Closing this issue. Let us know if any part is unresolved. Thanks!

**Closed by schilit** 2015-06-28 17:41 UTC
